name: SimpleAutoRestart
main: Main.Main
version: 0.0.1
api-version: 1.16
author: Limonchegggg#5387
commands:
    createMessage:
      description: Создание сообщений
      permission: SimpleAutoRestart.messages
    restartInfo:
      description: Просмотр оставшегося времени до рестарта
      permission: SimpleAutoRestart.restartInfo

permissions:
    SimpleAutoRestart.messages:
      description: Создание сообщений
    SimpleAutoRestart.restartInfo:
      description: Просмотр состояния сервера